{
"@R":"1371432070",
"eredirect":"",
"redirect":"",
"pre_action":"",
"post_action":"",
"session_exp":"2147483647",
"expires":"",
"header":"",
"pheader":"",
"bottom":"",
"layout":{
"type":"HorizontalWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://mongo-component/default/pages/page",
"children":[

]
},
"_u":"licence"
}