{
"@R":"1371432110",
"eredirect":"",
"redirect":"",
"pre_action":"",
"post_action":"",
"session_exp":"0",
"expires":"86400",
"header":"",
"pheader":"",
"layout":{
"type":"HorizontalWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://core-component/default/utils/notation",
"children":[

]
},
"_u":"notation",
"bottom":""
}