{
"@R":"1369623224",
"type":"JsonWidget",
"subject":"pages/edit_action",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"A.mongo\r
",
"action":[
"action://mongo-action/mongo/PageAction?set"
],
"header":"",
"bottom":"",
"_u":"pages/edit_action"
}